"""Track 2 (Task 8) — efc-row contact isolation on the live MJWarp CPU backend.

Reconstructs ``qfrc_constraint`` from the raw constraint (``efc``) rows exposed by
``mujoco_warp.Data``, then narrows that reconstruction to ONLY the rows generated by the
hammer<->nail contact pair. This is the foundation Task 9 builds on for a contact-rows-only
per-joint impulse metric that is immune to the dof-friction / joint-limit contamination described
in ``docs/research/reward-design/QFRC_MEASUREMENT_AUDIT.md``.

MEASURED LAYOUT (empirically pinned on this repo's env, CPU backend, mujoco_warp 3.8.1 —
the numbers below are this scene's; the STRUCTURE is a hard MJWarp-version fact, re-probe on
upgrade). All facts below were confirmed against the ``mujoco_warp._src.types`` dataclass
docstrings AND live probing (`d = env.sim.wp_data` during a driven strike):

* ``d.nacon``: ``wp.array`` of shape ``(1,)`` — the number of detected contacts **summed across
  ALL worlds** (a single global scalar, NOT per-world), capped at ``d.naconmax`` (capacity shared
  across worlds, e.g. 64 * nworld). Confirmed: with ``num_envs=2`` and one contact in each world,
  ``nacon == 2`` (not ``[1, 1]``).
* ``d.nefc``: ``wp.array`` of shape ``(nworld,)`` — the number of ACTIVE constraint rows,
  PER WORLD, capped at ``d.njmax`` (per-world capacity, e.g. 300 on this scene). This is the
  scalar the brief calls "nefc scalar or per-world" — measured answer: **per-world**.
* ``d.efc.J``: **DENSE**, shape ``(nworld, njmax_pad, nv)`` (measured ``(1, 304, 8)`` for
  ``num_envs=1``; ``njmax_pad`` = ``njmax`` rounded up to the GPU tile size — 304 = 300 rounded to
  the nearest multiple of 8 here — with NO functional meaning: rows ``[njmax, njmax_pad)`` are
  pure alignment padding never touched by ``force``/``type``, which stop at ``njmax``). Rows are
  laid out per-world in the leading dimension, so a row index is unambiguous once you know its
  world — this is WHY the ``efc`` struct carries no ``worldid`` field (unlike ``contact``, which
  is a single flat cross-world array and therefore needs one).
* The **sparse-index fields are ALWAYS EMPTY** on this backend: ``efc.J_rownnz`` and
  ``efc.J_rowadr`` measured shape ``(nworld, 0)``; ``efc.J_colind`` measured shape
  ``(nworld, 0, 0)``. This matches the mujoco_warp ``Constraint`` dataclass docstring verbatim:
  "J_rownnz: ... (nworld, 0) dense (nworld, njmax) sparse" (i.e. the sparse variant is a
  documented alternative layout, not the live one here). **Consequence: the per-row
  rownnz/rowadr/colind gather pseudocode in the task brief does not apply on this backend** —
  reconstruction below uses the dense row directly (every row already spans all ``nv`` columns,
  so "gathering the nonzero columns" is the identity operation and the masked dense sum is
  mathematically equivalent to summing ``J_row * force_row`` over active rows).
* **Overflow rows contain STALE, NONZERO garbage**, not zero — confirmed empirically (previous
  step's contact force values, magnitude ~10, were observed sitting past ``nefc`` on a step where
  those rows were inactive). The ``nefc <= njmax`` / ``nacon <= naconmax`` guards below are load-
  bearing, not defensive: a naive full-width sum would silently include a stale contact force
  from N steps ago. (Boundary per mujoco_warp's own docs: overflow is count **>** capacity —
  ``==`` is a valid fully-packed state, so the guards use ``<=``, not strict ``<``.)
* Row ordering is grouped by constraint TYPE within a world, not by C MuJoCo's construction order:
  observed order for the single-contact single-env case was 8 ``FRICTION_DOF`` rows (one per DOF,
  ``mujoco.mjtConstraint.mjCNSTR_FRICTION_DOF == 1``) followed by 3 ``CONTACT_ELLIPTIC`` rows
  (``mjCNSTR_CONTACT_ELLIPTIC == 7``). Never assume position — classify via ``efc.type``.
* **This scene's contact cone is ELLIPTIC, not pyramidal** (``efc.type == 7`` at the contact rows,
  confirmed against ``contact.dim == 3`` at the same contact): row count per contact ==
  ``dim`` (3), matching the "elliptic: dim rows" branch of the two hypothesized formulas —
  pyramidal's ``max(1, 2*(dim-1))`` does NOT apply here. ``contact.efc_address`` is padded to a
  fixed ``nmaxpyramid`` slot count regardless of cone (measured 4 slots on this scene: 3 valid
  indices + one ``-1`` sentinel for the unused 4th slot) — the helpers below filter on the ``-1``
  sentinel directly rather than re-deriving the row count from ``dim``/cone type, which is
  self-documenting from the data mujoco_warp already computed and robust if a future geom pair
  ever contacts with a different ``dim``.
* ``contact.geom``, ``contact.worldid``, ``contact.dim``, ``contact.efc_address``, ``contact.type``
  are all flat arrays of length ``naconmax`` spanning ALL worlds (unlike ``efc.*``, which is
  per-world-blocked) — ``contact.worldid[i]`` is the only way to know which world contact ``i``
  (and therefore which of its efc rows) belongs to. ``contact.type`` is a `ContactType` BITMASK
  (``CONSTRAINT = 1``, ``SENSOR = 2``) — NOT the friction-cone type (that's ``efc.type``/``dim``);
  only ``CONSTRAINT``-flagged contacts have valid (non -1) ``efc_address`` entries, so the
  ``-1`` filter above already excludes SENSOR-only contact entries as a side effect.
* Compiled geom ids are entity-prefixed and resolved via the HOST ``mujoco.MjModel``
  (``env.sim.mj_model.geom(name).id``), confirmed: ``robot/hammer_head_0`` = 18,
  ``robot/hammer_head_1`` = 19, ``nail_block/nail_shaft`` = 24, ``nail_block/nail_head`` = 25
  (``nail_block/block_geom`` = 23 is EXCLUDED per the task brief).
* ``arm_dof_cols``: the robot entity occupies GLOBAL dof columns ``[0, 7)`` (7 dofs: joint1-6 +
  jointGripper) on this scene (``nv`` totals 8 = 7 robot + 1 nail-slide dof; the robot happens to
  be the first entity in the compiled model, so its ``joint_v_adr`` happens to equal its
  entity-local index — this is NOT assumed, it is read live via ``Entity.indexing.joint_v_adr``).

Everything here is float32 (MJWarp's native dtype); the CPU backend is deterministic run-to-run
(no GPU atomic-ordering nondeterminism), but the invariant tolerance below is still the
float32-appropriate ``rtol=1e-4, atol=1e-6`` from the brief — never bit-compare.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import torch
import warp as wp

from mjlab.managers.scene_entity_config import SceneEntityCfg

if TYPE_CHECKING:
  from mjlab.envs import ManagerBasedRlEnv

ARM_JOINT_NAMES = ("joint1", "joint2", "joint3", "joint4", "joint5", "joint6")

# Entity-prefixed compiled geom names (task brief; nail_block/block_geom deliberately excluded —
# it is the wooden block, not a strikeable/struck surface).
_HAMMER_GEOM_NAMES = ("robot/hammer_head_0", "robot/hammer_head_1")
_NAIL_GEOM_NAMES = ("nail_block/nail_shaft", "nail_block/nail_head")

# mujoco_warp Contact.type is a `ContactType` IntFlag bitmask (CONSTRAINT=1, SENSOR=2); only
# CONSTRAINT-flagged contacts have live (non -1) efc_address rows.
_CONTACT_TYPE_CONSTRAINT_BIT = 1


def _resolve_contact_geom_ids(env: "ManagerBasedRlEnv") -> tuple[set[int], set[int]]:
  """Resolve the hammer-side / nail-side GLOBAL compiled geom ids by name.

  Uses the host ``mujoco.MjModel`` (``env.sim.mj_model``), since compiled geom ids in
  ``contact.geom`` are GLOBAL scene ids, not per-entity-local indices (which is what
  ``SceneEntityCfg.geom_ids`` would resolve to).
  """
  m = env.sim.mj_model
  hammer_ids = {int(m.geom(name).id) for name in _HAMMER_GEOM_NAMES}
  nail_ids = {int(m.geom(name).id) for name in _NAIL_GEOM_NAMES}
  return hammer_ids, nail_ids


def arm_dof_cols(env: "ManagerBasedRlEnv") -> torch.Tensor:
  """Return the GLOBAL dof-column indices (shape ``(6,)``, long) for the robot's arm joints
  (joint1..joint6, excluding jointGripper), in that order.

  These are the columns of the GLOBAL ``(num_envs, nv)`` qfrc/efc-column space that
  ``reconstruct_qfrc_from_efc``/``contact_row_qfrc`` operate in — NOT the entity-local
  ``SceneEntityCfg.joint_ids`` (which index into the robot's OWN ``_joint_dof_field`` view).
  """
  cfg = SceneEntityCfg("robot", joint_names=ARM_JOINT_NAMES)
  cfg.resolve(env.scene)
  robot = env.scene["robot"]
  cols = robot.indexing.joint_v_adr[cfg.joint_ids]
  return cols.long()


def reconstruct_qfrc_from_efc(env: "ManagerBasedRlEnv") -> torch.Tensor:
  """Reconstruct ``qfrc_constraint`` (shape ``(num_envs, nv)``) from ALL active efc rows.

  Ground-truth invariant: this must equal ``env.sim.wp_data.qfrc_constraint`` bit-for-bit
  (mod float32 rounding), since ``qfrc_constraint = efc.J^T @ efc.force`` summed over every
  active constraint row of every type (friction, limit, contact, ...) — see the module
  docstring for the measured dense-row layout this sums over.
  """
  d = env.sim.wp_data
  nefc = wp.to_torch(d.nefc).long()  # (nworld,) — PER-WORLD active row count.
  njmax = d.njmax
  # Boundary per mujoco_warp itself (collision_driver.py: overflow is count > capacity):
  # nefc == njmax is a legitimate fully-packed state; only > means rows were silently truncated.
  assert bool((nefc <= njmax).all()), (
    f"efc row overflow: nefc={nefc.tolist()} > njmax={njmax} — mujoco_warp silently "
    "truncates constraint rows past this cap; increase njmax in the sim cfg."
  )

  J = wp.to_torch(d.efc.J)  # (nworld, njmax_pad, nv) DENSE — see module docstring.
  force = wp.to_torch(d.efc.force)  # (nworld, njmax)
  nworld, njmax_live = force.shape
  nv = env.sim.wp_model.nv
  J = J[:, :njmax_live, :nv]  # drop the tile-alignment pad rows/cols, never touched by force.

  # Rows [nefc[w], njmax) hold STALE data from a previous step (measured, not assumed) — mask
  # them out rather than relying on them being zero.
  row_idx = torch.arange(njmax_live, device=force.device).unsqueeze(0)  # (1, njmax)
  active = row_idx < nefc.unsqueeze(1)  # (nworld, njmax)
  masked_force = torch.where(active, force, torch.zeros_like(force))

  return torch.einsum("wrc,wr->wc", J, masked_force)


def contact_row_qfrc(env: "ManagerBasedRlEnv") -> torch.Tensor:
  """Reconstruct ``qfrc_constraint`` (shape ``(num_envs, nv)``) using ONLY the efc rows that
  belong to a hammer<->nail contact (geom-pair filtered; see module docstring for the geom ids).

  Zero on any world/step with no hammer<->nail contact row active. Rows are attributed to their
  world via ``contact.worldid`` (the ``efc`` struct itself is already world-blocked by its
  leading dimension and carries no per-row world id — see module docstring).
  """
  d = env.sim.wp_data
  nacon = int(wp.to_torch(d.nacon)[0])  # GLOBAL scalar, summed across all worlds.
  naconmax = d.naconmax
  # Boundary per mujoco_warp itself (collision_driver.py:766-769: "If d.nacon is larger than
  # d.naconmax then an overflow has occurred and the remaining contacts will be skipped"):
  # nacon == naconmax is a legitimate fully-packed state; only > means silent truncation.
  assert nacon <= naconmax, (
    f"contact overflow: nacon={nacon} > naconmax={naconmax} — mujoco_warp silently "
    "truncates contacts past this cap; increase naconmax in the sim cfg."
  )

  nworld = d.nworld
  nv = env.sim.wp_model.nv
  out = torch.zeros(nworld, nv, dtype=torch.float32, device=env.device)
  if nacon == 0:
    return out

  hammer_ids, nail_ids = _resolve_contact_geom_ids(env)

  geom = wp.to_torch(d.contact.geom)[:nacon]  # (nacon, 2) global geom ids
  worldid = wp.to_torch(d.contact.worldid)[:nacon].long()  # (nacon,)
  ctype = wp.to_torch(d.contact.type)[:nacon]  # (nacon,) ContactType bitmask
  addr = wp.to_torch(d.contact.efc_address)[:nacon].long()  # (nacon, nmaxpyramid), -1 = unused

  J = wp.to_torch(d.efc.J)[:, :, :nv]  # (nworld, njmax_pad, nv)
  force = wp.to_torch(d.efc.force)  # (nworld, njmax)

  for i in range(nacon):
    g0, g1 = int(geom[i, 0]), int(geom[i, 1])
    spans_pair = (g0 in hammer_ids and g1 in nail_ids) or (
      g0 in nail_ids and g1 in hammer_ids
    )
    if not spans_pair:
      continue
    if not (int(ctype[i]) & _CONTACT_TYPE_CONSTRAINT_BIT):
      continue  # SENSOR-only contact entry: no live efc rows to attribute.
    w = int(worldid[i])
    for r in addr[i].tolist():
      if r < 0:
        continue  # padding sentinel (see module docstring: nmaxpyramid slot, unused for this dim)
      out[w] += J[w, r, :] * force[w, r]

  return out
